/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Principal;

import Vista.Protectora.Mascota.VentanaEditarMascota;
import Vista.Protectora.Mascota.VentanaEliminarMascota;
import Vista.Protectora.Mascota.VentanaListadoMascota;
import Vista.Protectora.Mascota.VentanaRegistroMascota;
import Vista.Protectora.VentanaEditarProtectora;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author UsuarioPracticas
 */
public class VentanaPrincipalProtectora extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipalProtectora
     */
    public VentanaPrincipalProtectora() {
        initComponents();
        setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/Resources/iconSC.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        jltitulo2 = new javax.swing.JLabel();
        jbCerrarSesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbModificarProtectora = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbListarMascotas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbEliminarMascota = new javax.swing.JButton();
        jbModificarMascota = new javax.swing.JButton();
        jbRegistrarMascota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Protectora");
        setSize(new java.awt.Dimension(600, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("Principal"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logoSC.png"))); // NOI18N
        jlLogo.setAlignmentY(0.0F);
        jPanel1.add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 190, 150));

        jltitulo2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jltitulo2.setText("Menu Principal");
        jPanel1.add(jltitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jbCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cerrarSesion.png"))); // NOI18N
        jbCerrarSesion.setToolTipText("Cerrar la sesión actual...");
        jbCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(jbCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 50, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 195, 166)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Protectora");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jbModificarProtectora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/modificar16px.png"))); // NOI18N
        jbModificarProtectora.setText("Editar");
        jbModificarProtectora.setToolTipText("Modificar datos de una mascota...");
        jbModificarProtectora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarProtectoraActionPerformed(evt);
            }
        });
        jPanel2.add(jbModificarProtectora, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 195, 166)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbListarMascotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/listados.png"))); // NOI18N
        jbListarMascotas.setText("Listado");
        jbListarMascotas.setToolTipText("Listar mascotas...");
        jbListarMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarMascotasActionPerformed(evt);
            }
        });
        jPanel3.add(jbListarMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mascotas");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jbEliminarMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/borrar.png"))); // NOI18N
        jbEliminarMascota.setText("Eliminar");
        jbEliminarMascota.setToolTipText("Eliminar mascota...");
        jbEliminarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarMascotaActionPerformed(evt);
            }
        });
        jPanel3.add(jbEliminarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 110, 40));

        jbModificarMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/modificar16px.png"))); // NOI18N
        jbModificarMascota.setText("Editar");
        jbModificarMascota.setToolTipText("Modificar datos de una mascota...");
        jbModificarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarMascotaActionPerformed(evt);
            }
        });
        jPanel3.add(jbModificarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 110, 40));

        jbRegistrarMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/añadir.png"))); // NOI18N
        jbRegistrarMascota.setText("Registrar");
        jbRegistrarMascota.setToolTipText("Registrar mascota...");
        jbRegistrarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarMascotaActionPerformed(evt);
            }
        });
        jPanel3.add(jbRegistrarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 290, 140));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 310, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 600, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbModificarProtectoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarProtectoraActionPerformed
        // TODO add your handling code here:
        VentanaEditarProtectora vEditarProtectora = new VentanaEditarProtectora();
        this.setVisible(false);
        vEditarProtectora.setVisible(true);
    }//GEN-LAST:event_jbModificarProtectoraActionPerformed

    private void jbModificarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarMascotaActionPerformed
        VentanaEditarMascota vEditarMascota = new VentanaEditarMascota();
        this.setVisible(false);
        vEditarMascota.setVisible(true);
    }//GEN-LAST:event_jbModificarMascotaActionPerformed

    private void jbRegistrarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarMascotaActionPerformed
        VentanaRegistroMascota vRegistroMascota = new VentanaRegistroMascota();
        this.setVisible(false);
        vRegistroMascota.setVisible(true);
    }//GEN-LAST:event_jbRegistrarMascotaActionPerformed

    private void jbCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarSesionActionPerformed
        VentanaLogin vLogin = new VentanaLogin();
        this.setVisible(false);
        vLogin.setVisible(true);
    }//GEN-LAST:event_jbCerrarSesionActionPerformed

    private void jbListarMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarMascotasActionPerformed
        VentanaListadoMascota vListadoMascota = new VentanaListadoMascota();
        this.setVisible(false);
        vListadoMascota.setVisible(true);
    }//GEN-LAST:event_jbListarMascotasActionPerformed

    private void jbEliminarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarMascotaActionPerformed
        VentanaEliminarMascota vEliminarMascota = new VentanaEliminarMascota();
        this.setVisible(false);
        vEliminarMascota.setVisible(true);
    }//GEN-LAST:event_jbEliminarMascotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalProtectora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalProtectora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalProtectora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalProtectora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalProtectora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbCerrarSesion;
    private javax.swing.JButton jbEliminarMascota;
    private javax.swing.JButton jbListarMascotas;
    private javax.swing.JButton jbModificarMascota;
    private javax.swing.JButton jbModificarProtectora;
    private javax.swing.JButton jbRegistrarMascota;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jltitulo2;
    // End of variables declaration//GEN-END:variables
}
