/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Protectora.Consulta;

import Controlador.GestionarConsulta;
import Modelo.Consulta;
import Modelo.Protectora;
import Vista.Principal.VentanaPrincipalProtectora;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author UsuarioPracticas
 */
public class VentanaListadoConsulta extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    private static Protectora protectora;

    /**
     * Creates new form VentanaListadoMascota
     * @param protectora Protectora logeada
     */
    public VentanaListadoConsulta(Protectora protectora) {
        initComponents();
        this.protectora = protectora;
        modelo = new DefaultTableModel();
        jtConsulta.getTableHeader().setFont(new Font("TAHOMA", Font.PLAIN, 14));
        rellenarTabla();
        setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/Resources/iconSC.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlError = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jbListar = new javax.swing.JButton();
        jbVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfCodConsulta = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsulta = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaInformacion = new javax.swing.JTextArea();
        jltitulo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listar Consultas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jlError, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logoSC.png"))); // NOI18N
        jPanel1.add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jlTitulo.setFont(new java.awt.Font("Segoe Print", 0, 52)); // NOI18N
        jlTitulo.setText("Second Chance");
        jPanel1.add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jbListar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/listados.png"))); // NOI18N
        jbListar.setText("Listar");
        jbListar.setToolTipText("Pulse este boton para listar las consultas...");
        jbListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarActionPerformed(evt);
            }
        });
        jPanel1.add(jbListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, -1, -1));

        jbVolver.setBackground(new java.awt.Color(255, 255, 255));
        jbVolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/volver.png"))); // NOI18N
        jbVolver.setToolTipText("Pulse este boton para ir al menu principal...");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });
        jPanel1.add(jbVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        jLabel1.setText("Codigo Consulta:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        jtfCodConsulta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfCodConsultaFocusGained(evt);
            }
        });
        jtfCodConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCodConsultaKeyTyped(evt);
            }
        });
        jPanel1.add(jtfCodConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 140, 30));

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/busqueda25px.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, -1, 30));

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtConsulta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Consulta", "Código Mascota", "DNI Voluntario", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtConsulta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, 210));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

        jtaInformacion.setEditable(false);
        jtaInformacion.setColumns(20);
        jtaInformacion.setLineWrap(true);
        jtaInformacion.setRows(5);
        jScrollPane2.setViewportView(jtaInformacion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 450, -1));

        jltitulo3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jltitulo3.setText("Listado de Consultas");
        jPanel1.add(jltitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarActionPerformed
        // TODO add your handling code here:
        jtfCodConsulta.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jtfCodConsulta.setText("");
        vaciarTabla();
        rellenarTabla();
    }//GEN-LAST:event_jbListarActionPerformed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        VentanaPrincipalProtectora vPrincipalProtectora = new VentanaPrincipalProtectora();
        this.setVisible(false);
        vPrincipalProtectora.setVisible(true);
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        if (!jtfCodConsulta.getText().isEmpty()) {
            vaciarTabla();
            buscarConsulta();
        } else {
            jtfCodConsulta.setBorder(new LineBorder(Color.red, 1));
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jtfCodConsultaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodConsultaFocusGained
        // TODO add your handling code here:
        jtfCodConsulta.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
    }//GEN-LAST:event_jtfCodConsultaFocusGained
    /**
     * Metodo para solo poder introducir numeros en el JTextField
     */
    private void jtfCodConsultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodConsultaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCodConsultaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaListadoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaListadoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaListadoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaListadoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaListadoConsulta(protectora).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbListar;
    private javax.swing.JButton jbVolver;
    private javax.swing.JLabel jlError;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jltitulo3;
    private javax.swing.JTable jtConsulta;
    private javax.swing.JTextArea jtaInformacion;
    private javax.swing.JTextField jtfCodConsulta;
    // End of variables declaration//GEN-END:variables

    private void vaciarTabla() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        jtaInformacion.setText("");
    }

    private void rellenarTabla() {
        ArrayList<Consulta> alConsultas = GestionarConsulta.listarConsultasCifProtectora(protectora.getCif());
        modelo = (DefaultTableModel) jtConsulta.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < alConsultas.size(); i++) {
            ob[0] = alConsultas.get(i).getCodConsulta();
            ob[1] = alConsultas.get(i).getCodMascota();
            ob[2] = alConsultas.get(i).getDniVoluntario();
            ob[3] = alConsultas.get(i).getHorario();
            ob[4] = alConsultas.get(i).getInformacion();
            modelo.addRow(ob);
        }
        jtConsulta.setModel(modelo);
    }

    private void buscarConsulta() {
        try {
            Consulta consulta = GestionarConsulta.obtenerConsultaCodCifProtectora(jtfCodConsulta.getText(), protectora.getCif());
            modelo = (DefaultTableModel) jtConsulta.getModel();
            Object[] ob = new Object[5];
            ob[0] = consulta.getCodConsulta();
            ob[1] = consulta.getCodMascota();
            ob[2] = consulta.getDniVoluntario();
            ob[3] = consulta.getHorario();
            ob[4] = consulta.getInformacion();
            modelo.addRow(ob);
            jtConsulta.setModel(modelo);
            jtaInformacion.setText(ob[4].toString());
            jlError.setText("");
        } catch (NullPointerException e) {
            jlError.setText("¡La consulta no existe!");
        }

    }
}
