/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Protectora;

import Controlador.GestionarProtectora;
import Modelo.Protectora;
import Vista.Principal.VentanaPrincipalAdmin;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author UsuarioPracticas
 */
public class VentanaListadoProtectora extends javax.swing.JFrame {
    
    private DefaultTableModel modelo;

    /**
     * Creates new form VentanaRegistro
     */
    public VentanaListadoProtectora() {
        initComponents();
        jtProtectoras.getTableHeader().setFont(new Font("TAHOMA", Font.PLAIN, 14));
        modelo = new DefaultTableModel();
        rellenarTabla();
        setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/Resources/iconSC.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlError = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jbListar = new javax.swing.JButton();
        jbVolver1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProtectoras = new javax.swing.JTable();
        jtfCif = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jltitulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listar Protectoras");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jlError, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logoSC.png"))); // NOI18N
        jPanel1.add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        jlTitulo.setFont(new java.awt.Font("Segoe Print", 0, 52)); // NOI18N
        jlTitulo.setText("Second Chance");
        jPanel1.add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jbListar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/listados.png"))); // NOI18N
        jbListar.setText("Listar");
        jbListar.setToolTipText("Pulse este boton para listar las protectoras...");
        jbListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarActionPerformed(evt);
            }
        });
        jPanel1.add(jbListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, -1, -1));

        jbVolver1.setBackground(new java.awt.Color(255, 255, 255));
        jbVolver1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/volver.png"))); // NOI18N
        jbVolver1.setToolTipText("Pulse este boton para ir al menu principal...");
        jbVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolver1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jtProtectoras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtProtectoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CIF", "Nombre", "Razon Social", "email", "Teléfono", "Ubicación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtProtectoras);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 550, 220));

        jtfCif.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfCifFocusGained(evt);
            }
        });
        jPanel1.add(jtfCif, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 140, 30));

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/busqueda25px.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CIF:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        jltitulo2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jltitulo2.setText("Listado de Protectoras");
        jPanel1.add(jltitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarActionPerformed
        // TODO add your handling code here:
        jtfCif.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jtfCif.setText("");
        vaciarTabla();
        rellenarTabla();
    }//GEN-LAST:event_jbListarActionPerformed

    private void jbVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolver1ActionPerformed
        VentanaPrincipalAdmin vPrincipalAdmin = new VentanaPrincipalAdmin();
        this.setVisible(false);
        vPrincipalAdmin.setVisible(true);
    }//GEN-LAST:event_jbVolver1ActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        if (!jtfCif.getText().isEmpty()) {
            vaciarTabla();
            buscarProtectora();
            jtfCif.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        } else {
            jtfCif.setBorder(new LineBorder(Color.red));
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jtfCifFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCifFocusGained
        // TODO add your handling code here:
        jtfCif.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        jlError.setText("");

    }//GEN-LAST:event_jtfCifFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaListadoProtectora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaListadoProtectora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaListadoProtectora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaListadoProtectora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaListadoProtectora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbListar;
    private javax.swing.JButton jbVolver1;
    private javax.swing.JLabel jlError;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jltitulo2;
    private javax.swing.JTable jtProtectoras;
    private javax.swing.JTextField jtfCif;
    // End of variables declaration//GEN-END:variables

    private void vaciarTabla() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
    
    private void rellenarTabla() {
        ArrayList<Protectora> alProtectoras = GestionarProtectora.listarProtectora();
        modelo = (DefaultTableModel) jtProtectoras.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < alProtectoras.size(); i++) {
            ob[0] = alProtectoras.get(i).getCif();
            ob[1] = alProtectoras.get(i).getNombreProtectora();
            ob[2] = alProtectoras.get(i).getRazonSocial();
            ob[3] = alProtectoras.get(i).getEmail();
            ob[4] = alProtectoras.get(i).getTelefono();
            ob[5] = alProtectoras.get(i).getUbicacion();
            modelo.addRow(ob);
        }
        jtProtectoras.setModel(modelo);
    }
    
    private void buscarProtectora() {
        try {
            Protectora protectora = GestionarProtectora.obtenerProtectoraCif(jtfCif.getText());
            modelo = (DefaultTableModel) jtProtectoras.getModel();
            Object[] ob = new Object[6];
            ob[0] = protectora.getCif();
            ob[1] = protectora.getNombreProtectora();
            ob[2] = protectora.getRazonSocial();
            ob[3] = protectora.getEmail();
            ob[4] = protectora.getTelefono();
            ob[5] = protectora.getUbicacion();
            modelo.addRow(ob);
            jtProtectoras.setModel(modelo);
            jlError.setText("");
            
        } catch (NullPointerException e) {
            jlError.setText("¡¡La protectora no existe!!");
        }
        
    }
}
